aws_region               = "eu-west-1"
project_id               = "cmtr-b56386db"
aws_launch_template_name = "cmtr-b56386db-template"
aws_asg_name             = "cmtr-b56386db-asg"
load_balancer_name       = "cmtr-b56386db-loadbalancer"
